server:
  port: 0
  shutdown: graceful
# ===============================
# = Application Info
# ===============================
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: BMRS-XML-Parser
  # ===============================
  # = Multipart File Upload Limits
  # ===============================
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


info:
  app:
    name: BMRS-XML-Parser-service
    description: This service is responsible for parsing and inserting XML data in database
    version: 1.0

# ===============================
# = Logging Configuration
# ===============================
logging:
  level:
    root: INFO
    com.biometric.fingerprint: DEBUG
    org.springframework.web: WARN
  file:
    path: logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
